# Generated by Django 6.0.3 on 2026-04-30 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1), help_text='Data de nascimento. Usada para verificar restrições de idade em cursos e identificar menores que precisem de autorização.'),
            preserve_default=False,
        ),
    ]
