# Generated by Django 6.0.3 on 2026-05-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_is_private_lesson_label'),
        ('enrollments', '0002_student_birth_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_active_enrolment',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Prazo para o pagamento ser confirmado. Se status ainda for 'pending' após este horário, vira 'expired' e a vaga é liberada.", null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['rejected', 'expired']), _negated=True), fields=('student', 'lesson'), name='unique_active_enrolment'),
        ),
    ]
