# Generated by Django 6.0.3 on 2026-05-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_remove_enrollment_unique_active_enrolment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='donation_type',
            field=models.CharField(blank=True, choices=[('dog_food', 'Ração de Cachorro'), ('cat_food', 'Ração de Gato'), ('bird_food', 'Ração de Pássaro')], help_text="Tipo de ração doada. Obrigatório quando payment_method é 'donation_item' ou 'hybrid'.", max_length=20),
        ),
    ]
