# Generated by Django 6.0.3 on 2026-05-01 06:25

import enrollments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_payment_donation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=enrollments.models.default_enrollment_expiration, help_text="Prazo para o pagamento ser confirmado. Se status ainda for 'pending' após este horário, vira 'expired' e a vaga é liberada.", null=True),
        ),
    ]
