# Generated by Django 6.0.3 on 2026-05-01 19:35

import django.db.models.deletion
import enrollments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_hire_date_alter_employee_role_and_more'),
        ('courses', '0007_alter_course_status'),
        ('enrollments', '0006_alter_enrollment_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da inscrição'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=enrollments.models.default_enrollment_expiration, help_text="Prazo para confirmar o pagamento. Após esse horário, inscrições pendentes viram 'expirada' e a vaga é liberada.", null=True, verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_overbooked',
            field=models.BooleanField(default=False, help_text='Marcado quando um admin força a inscrição mesmo com a turma cheia.', verbose_name='Overbooking'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.lesson', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='enrollments.student', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Funcionário que validou o pagamento. Obrigatório para pagamentos presenciais.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee', verbose_name='Aprovado por'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='donation_type',
            field=models.CharField(blank=True, choices=[('dog_food', 'Ração de cachorro'), ('cat_food', 'Ração de gato'), ('bird_food', 'Ração de pássaro')], help_text="Tipo de ração doada. Obrigatório quando o método é 'Doação de ração' ou 'Híbrido'.", max_length=20, verbose_name='Tipo de doação'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='enrollments.enrollment', verbose_name='Inscrição'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='item_quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade doada (kg)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='money_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Cartão de crédito'), ('pix', 'Pix'), ('cash', 'Dinheiro'), ('donation_item', 'Doação de ração'), ('hybrid', 'Híbrido (dinheiro + ração)'), ('scholarship', 'Bolsa')], max_length=20, verbose_name='Método de pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_origin',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'Presencial')], default='online', max_length=10, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado')], default='pending', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(help_text='Usada para verificar restrições de idade em cursos e identificar menores que precisem de autorização.', verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(max_length=20, verbose_name='Contato de emergência'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
