# Generated by Django 6.0.3 on 2026-05-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['employee__user__first_name'], 'verbose_name': 'Instrutor', 'verbose_name_plural': 'Instrutores'},
        ),
    ]
