# Generated by Django 6.0.3 on 2026-04-08 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['employee__user__first_name'], 'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
    ]
