# Generated by Django 6.0.3 on 2026-05-01 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_options_alter_instructor_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name='Data de contratação'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='bio',
            field=models.TextField(blank=True, help_text='Breve currículo do instrutor.', verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='specialty',
            field=models.CharField(help_text='Ex: Biologia marinha, Trilhas, Educação ambiental, etc.', max_length=100, verbose_name='Especialidade'),
        ),
    ]
