# Generated by Django 6.0.3 on 2026-05-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Turma fechada: não aparece na listagem pública e só admin pode inscrever alunos.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='label',
            field=models.CharField(blank=True, help_text="Nome opcional da turma (ex: 'Turma escola Eusébio Farias'). Se vazio, usa numeração automática.", max_length=100),
        ),
    ]
