# Generated by Django 6.0.3 on 2026-05-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_options_alter_instructor_options'),
        ('courses', '0004_alter_course_options_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='donation_kg_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantos kg de ração são exigidos como parte do pagamento. Deixe vazio se não exigir doação.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=True, help_text='Curso emite certificado ao final?'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL pública da imagem de capa do curso (ex: hospedada no Cloudinary, S3, Imgur).'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(help_text='Instrutores que ministram este curso. Pelo menos 1.', related_name='courses', to='accounts.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, help_text='Idade mínima exigida para inscrição. Deixe vazio se não houver restrição.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Roteiro/conteúdo programático do curso. Aceita Markdown (## títulos, - bullets, **negrito**).'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Resumo curto do curso (1-2 parágrafos). Aparece em cards e topo da página de detalhes.'),
        ),
    ]
