# Generated by Django 6.0.3 on 2026-05-01 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_options_alter_instructor_options'),
        ('courses', '0005_course_donation_kg_required_course_has_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_url',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem que aparece no card e na página de detalhes do curso.', null=True, upload_to='courses/', verbose_name='Imagem de capa'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Resumo curto do curso (1-2 parágrafos). Aparece em cards e topo da página de detalhes.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='course',
            name='donation_kg_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantos kg de ração são exigidos como parte do pagamento. Deixe vazio se não exigir doação.', max_digits=6, null=True, verbose_name='Doação exigida (kg)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.IntegerField(verbose_name='Duração (horas)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=True, help_text='O curso entrega certificado ao final?', verbose_name='Emite certificado'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(help_text='Instrutores que ministram este curso. Pelo menos 1.', related_name='courses', to='accounts.instructor', verbose_name='Instrutores'),
        ),
        migrations.AlterField(
            model_name='course',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, help_text='Idade mínima exigida para inscrição. Deixe vazio se não houver restrição.', null=True, verbose_name='Idade mínima'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Conteúdo programático do curso. Aceita Markdown (## títulos, - bullets, **negrito**).', verbose_name='Roteiro'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='capacity',
            field=models.IntegerField(verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='courses.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='accounts.instructor', verbose_name='Instrutor'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Turma fechada: não aparece na listagem pública e só admin pode inscrever alunos.', verbose_name='Turma fechada'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='label',
            field=models.CharField(blank=True, help_text="Nome opcional da turma (ex: 'Turma escola Eusébio Farias'). Se vazio, usa numeração automática.", max_length=100, verbose_name='Nome da turma'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(verbose_name='Início'),
        ),
    ]
