# Generated by Django 6.0.3 on 2026-05-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_image_url_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
