# Generated by Django 6.0.3 on 2026-05-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identificação interna do banner. Não aparece para o visitante.', max_length=100, verbose_name='Nome interno')),
                ('image', models.ImageField(help_text='Imagem de fundo do banner. Recomendado pelo menos 1920x600 px.', upload_to='banners/', verbose_name='Imagem')),
                ('title', models.CharField(blank=True, help_text='Título principal do banner. Aparece em destaque sobre a imagem.', max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Texto secundário do banner.', max_length=200, verbose_name='Subtítulo')),
                ('link_url', models.URLField(blank=True, help_text='URL para onde o banner leva quando clicado. Deixe vazio para banner não-clicável.', verbose_name='Link de destino')),
                ('link_label', models.CharField(blank=True, help_text="Texto do botão de ação (ex: 'SAIBA MAIS'). Só aparece se houver link.", max_length=40, verbose_name='Texto do botão')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Posição na rotação do carrossel. Menor número aparece primeiro.', verbose_name='Ordem de exibição')),
                ('start_date', models.DateField(blank=True, help_text='Data a partir da qual o banner começa a aparecer. Vazio = sempre.', null=True, verbose_name='Início da exibição')),
                ('end_date', models.DateField(blank=True, help_text='Data até quando o banner aparece. Vazio = sem expiração.', null=True, verbose_name='Fim da exibição')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
